spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 50000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
            show_sql: true
            use_sql_comments: true
        open-in-view: false
    
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    com.todoapp.backend: DEBUG
    org.hibernate.SQL: DEBUG